public class ItemGetNfServiceResponse {

	 public String codigoItem;
	 public String descricao;
	 public Integer quantidade;
	 public Decimal valor;
	 public Decimal baseIcms;
	 public Decimal percentIcms;
	 public Decimal percentIpi;
	 
	 public String uniqueId;
	 public String strInvoiceIdValue;
	 public CabecalhoGetNfServiceResponse headerData;
	 public boolean selected;
	 public Integer quantidadeInformada;
	 
}