@isTest
/*******************************************************************************
*                     Copyright (C) 2013 - Cloud2b
*-------------------------------------------------------------------------------
* COVERAGE TEST FOR LogLimits.cls
* 
* NAME: LogLimitsTest.cls
* AUTHOR: CARLOS CARVALHO                         DATE: 14/02/2013
*
*******************************************************************************/
private class LogLimitsTest {

    static testMethod void myUnitTest() {
    	//Invoke LogLimits method for test
    	LogLimits.print('Execute test', true);
    }
}