public with sharing class PesquisaSatisfacaoLivroTO {

    public String Pergunta1 {get;set;}
    public String AvaliaLivro {get;set;}
    public String Pergunta2 {get;set;}
    public String adotaLivro  {get;set;}
    public String Pergunta3 {get;set;}
    public String salaVirtual  {get;set;}
    public String Pergunta4 {get;set;}
    public String seNao {get;set;}
    public String Pergunta5 {get;set;}
    public String seSim {get;set;}
    public String Pergunta6 {get;set;}
    public String recomenda {get;set;}
    public String Pergunta7 {get;set;}
    public String comentario {get;set;}
    public String respEmailId {get;set;}
    
}