public with sharing class PesquisaSatisfacaoTO {

    public String Pergunta1 {get;set;}
    public String Resposta1 {get;set;}
    public String Pergunta2 {get;set;}
    public String Resposta2 {get;set;}
    public String Pergunta3 {get;set;}
    public String Resposta3 {get;set;}
    public String Pergunta4 {get;set;}
    public String Resposta4 {get;set;}
    public String Pergunta5 {get;set;}
    public String Resposta5 {get;set;}
    public String Pergunta6 {get;set;}
    public String Resposta6 {get;set;}
    public String Pergunta7 {get;set;}
    public String Resposta7 {get;set;}
    
    public String Pergunta8 {get;set;}
    public String Resposta8 {get;set;}
    public String Pergunta9 {get;set;}
    public String Resposta9 {get;set;}
    public String Pergunta10 {get;set;}
    public String Resposta10 {get;set;}

    public String Pergunta11 {get;set;}
    public String Resposta11 {get;set;}
    
    public String respEmailId {get;set;}
    
}